export const FieldMap = {
    savingsType: "Savings type",
    creationConfirmed: "Creation hash",
    settleConfirmed: "Settle hash",
    customerID: "Customer ID",
    savingsAccountID: "Savings account ID",
    savingsType: "Savings type",
    savingsPeriod: "Savings period",
    interestRate: "Interest rate",
    savingsAmount: "Savings amount",
    estimatedInterestAmount: "Estimated interest amount",
    actualInterestAmount: "Actual interest amount",
    settleInstruction: "Settle instruction",
    currency: "Currency",
    openTime: "Open time",
    settleTime: "Settle time",
}